version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: django-q
    versions:
    - 1.3.4
  - dependency-name: rope
    versions:
    - 0.18.0
- package-ecosystem: docker
  directory: "/nginx"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine3.11
    - 15.11.0.pre.alpine3.11
    - 15.12.0.pre.alpine3.11
    - 15.13.0.pre.alpine3.11
    - 15.14.0.pre.alpine3.11
    - 15.7.0.pre.alpine3.11
    - 15.8.0.pre.alpine3.11
    - 15.9.0.pre.alpine3.11
  - dependency-name: nginx
    versions:
    - 1.19.6.pre.alpine
    - 1.19.7.pre.alpine
    - 1.19.8.pre.alpine
    - 1.19.9.pre.alpine
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: alpine
    versions:
    - "> 3.11.6, < 4"
